In [15]:
import numpy as np
import scipy.linalg as la

In [22]:
spinup = np.array([1,0])
spindown = np.array([0,1])

In [12]:
sigma_z = np.array([[1,0],
                    [0,-1]])
sigma_x = np.array([[0,1],
                    [1,0]])
sigma_y = np.array([[0,1.j],
                   [-1.j,0]])

In [7]:
sigma_z @ spinup

array([1, 0])

In [8]:
sigma_z @ sigma_z

array([[1, 0],
       [0, 1]])

In [9]:
sigma_x = np.array([[0,1],
                    [1,0]])

In [10]:
def commutator(A,B):
    return A @ B - B @ A

In [11]:
commutator(sigma_z,sigma_x)

array([[ 0,  2],
       [-2,  0]])

In [13]:
2.j * sigma_y

array([[ 0.+0.j, -2.+0.j],
       [ 2.-0.j,  0.+0.j]])

In [20]:
la.expm(1.j * np.pi * sigma_z / 2.)

array([[-0.+1.j, -0.+0.j],
       [ 0.+0.j,  0.-1.j]])

In [23]:
np.vdot(spinup,spindown)

0

In [27]:
sy = np.array([1,1.j])/np.sqrt(2)

In [28]:
np.dot(sy,sy)

0j

In [29]:
np.vdot(sy,sy)

(0.99999999999999978+0j)

In [30]:
np.kron(spinup,spindown) + np.kron(spindown,spinup)

array([0, 1, 1, 0])

In [31]:
def hamil(B):
    return B[0]*sigma_x + B[1]*sigma_y + B[2]*sigma_z