In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import scipy as sp
from scipy import linalg

A circulant matrix is a matrix that has circularly shifted rows or columns. This kind of matrix is the right kind to describe a translation invariant periodic system.

linalg.circulant takes the first column of the matrix as an argument and produces the corresponding circulant matrix

Refs:
https://en.wikipedia.org/wiki/Circulant_matrix
https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.linalg.circulant.html

In [2]:
firstcol = np.array([5,3,1,8])
C = linalg.circulant(firstcol)
print(C)

[[5 8 1 3]
 [3 5 8 1]
 [1 3 5 8]
 [8 1 3 5]]


Build the matrix for equations of motion for N balls of mass m and spring constant k placed into a loop.

In [ ]:
N = 10
k = 1.0
m = 1.0

#uncomment the following line and fill in the first column
#firstcol = np.array([   ])
K = linalg.circulant(firstcol)